version: '3'

services:
  stable-diffusion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860" # Web UI port
    volumes:
      - ./stable-diffusion-webui-forge/models:/app/stable-diffusion-webui-forge/models
      - ./stable-diffusion-webui-forge/outputs:/app/stable-diffusion-webui-forge/outputs
      - ./stable-diffusion-webui-forge/extensions:/app/stable-diffusion-webui-forge/extensions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
